In [3]:
#Задание 1

import numpy as np

N=int(input())
x=np.arange(N-1, -1, -1)
print(x)

10
[9 8 7 6 5 4 3 2 1 0]


In [5]:
#Задание 2

N=int(input())
mat=np.diag(np.arange(N-1, -1, -1)) 
print(mat)

6
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


In [6]:
# Задание 3

from numpy import linalg

a=np.array([[4, 2, 1], [2, 3, 1], [0, 5, 4]])
b=np.array([4, 12, -3])
linalg.solve(a, b)



array([ -0.22727273,   7.54545455, -10.18181818])

In [23]:
# Задание 4

import matplotlib.pyplot as plt 

users_stats=np.array(
    [ [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32)
    
    

    
    

In [24]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [27]:
print([np.dot( user, next_user_stats ) / (np.linalg.norm( user ) * np.linalg.norm( next_user_stats )) for user in users_stats])

[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]


In [31]:
#Самый похожий пользователь под номеров 8 со значением косинуса 0.9486832980505138


0
